phases:
  pre_build:
    commands:
      - mvn clean install
      - echo Logging into Amazon ECR
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      # Give URI that you have copied from AWS ECR Repositoty
      - REPOSITORY_URI= 304340177988.dkr.ecr.us-east-1.amazonaws.com/javatechieregistry1
      - COMMIT_HASH=$(echo $CODE_BUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '(print $2))
  build:
    commands:
      - echo Build started on "date"
      - echo Building the docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo "Build Completed on "date"
      - echo pushing the docker images
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"amssample","imageUri":%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - target/awsservice.jar
